### ISSUE TITLE
Installation requirement easygui not mentioned in documentation

### ISSUE THREAD

**Issue by laurenfitch** [aditya-88/ASAP#1]
Hi, thanks for putting this app out, it looks very useful! I installed all prerequisites and tried to run ASAP_installer.py but got the following error:

```root@d41383ffcf81:/biopython/ASAP# python ASAP_installer.py 
Traceback (most recent call last):
  File "ASAP_installer.py", line 5, in <module>
    import easygui
ImportError: No module named 'easygui'
```

I was able to resolve that error by installing easygui, but running ASAP_installer.py produced another error that I'm not sure how to resolve:
```root@e0e3e2c96934:/biopython# python ASAP/ASAP_installer.py 
Traceback (most recent call last):
  File "ASAP/ASAP_installer.py", line 9, in <module>
    choice = easygui.boolbox(msg='Do you wish to install ASAP ?', title=' ', choices=('Continue', 'Exit'), image=directory+"/asap.gif")
  File "/usr/local/lib/python3.5/dist-packages/easygui/boxes/derived_boxes.py", line 155, in boolbox
    cancel_choice=cancel_choice)
  File "/usr/local/lib/python3.5/dist-packages/easygui/boxes/button_box.py", line 102, in buttonbox
    callback=callback)
  File "/usr/local/lib/python3.5/dist-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/usr/local/lib/python3.5/dist-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by addityea** [comment]
Hi Lauren!
First of all, thank you for considering this code in your work and reporting back the errors.

I’ll definitely help you out on this.

The second issue is regarding Tk unable to find “DISPLAY”.
Which system are you using ?

You can try running one of these commands to fix the issue.

export DISPLAY=:0
Or
export DISPLAY=0.0
Or
export DISPLAY=:0.0
If one of these work, you can safely add it to the .bashrc of your system.

Hope it helps. Let me know.

Cheers!

**Comment by laurenfitch** [comment]
Thanks Aditya. It's not working for me at the moment, I think because I'm running it in a Docker container and it needs some additional configuration. Probably not ASAP-specific. Thanks for your help!

**Comment by addityea** [comment]
I’m not an expert of Docker but I would suggest:
After exporting the “Display” parameter as described above, try the following for running your Docker image:

docker run -it -e DISPLAY=$DISPLAY (followed by your image and other arguments)

Hope it helps.

**Comment by addityea** [comment]
I'm closing this issue for now.
If you encounter new issue(s), kindly feel free to begin a new thread.

Thanking you for your report back.
