### ISSUE TITLE
Executing the command

### ISSUE THREAD

**Issue by antra14** [aditya-88/ASAP#4]
Hi,
I am using this command to execute the script "./ASAP_0.33.py FR ../../430645_V3V4_F_H03_2021-12-20.ab1 ../../430645_V3V4_R_H09_2021-12-20.ab1" but I am not getting what will be reference.fasta file and how will I get the output files.

Could you  guide me for execution of script.

**Comment by addityea** [comment]
Hi!
Apologies for delay in response, but we are having a winter vacation here at the Univ!

Coming back to your question:

Reference.fasta is the reference sequence you wish to align your samples with.
Generally, it's the reference sequence of the gene you're sequencing from your samples.

For example:

If you're sequencing TMPRSS6 gene from human samples, you'll need TMPRSS6 reference sequence fasta file to align your sequencing reads (.ab1) files to.

Hope it helps,

Best,


Aditya
